In [1]:
import pandas as pd
import numpy as np
import csv
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

from sklearn import model_selection, svm
from sklearn.model_selection import KFold

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder

from scipy.sparse import csr_matrix as matrixTransform

# Input Data

In [2]:
df = pd.read_csv("D:\dataset_ta\Preprocessing\hasil_imb.csv")
df

     label                                             Review
0        0                                   nyesel lagijorok
1        0                           kartu kunci hrsnya kamar
2        0  bilang skrg layan ama skrg dsni masalah sarap ...
3        0  bagus harga segitu lokasi super strategis mesj...
4        0                             nyaman aman ac berisik
..     ...                                                ...
945      1                        over allah bagus ramah staf
946      1                          kamar bersih harga proper
947      1                                   nyaman strategis
948      1                                 bagus kamar bersih
949      1                           tempat bersih luas bagus

[950 rows x 2 columns]

# TF-IDF

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer 

tf_idf = TfidfVectorizer(binary=True)
tfidf_mat = tf_idf.fit_transform(df["Review"]).toarray()

In [4]:
tfidf = pd.DataFrame(tfidf_mat, columns=tf_idf.get_feature_names())
tfidf

C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,aah,aayang,abis,abu,ac,acar,acara,acnya,acsama,ad,...,yeyet,yidak,ynag,yogya,you,your,yudha,yuu,zaman,zonk
0,0.0,0.0,0.000000,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.000000,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.162711,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.000000,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.000000,0.0,0.4712,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,0.0,0.0,0.000000,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
946,0.0,0.0,0.000000,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
947,0.0,0.0,0.000000,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
948,0.0,0.0,0.000000,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
949,0.0,0.0,0.000000,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
X = tfidf.values
y = df['label']
X

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.16271069, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

# Klasifikasi Menggunakan Algoritma Support Vector Machine

In [6]:
class myClass:
    def __init__(self):
        self.recall = 0
        self.acc = 0
        self.pres = 0
    def getRecall(self):
        return self.recall
    def getPres(self):
        return self.pres
    def setRecall(self, recall):
        self.recall = recall
    def setPres(self, pres):
        self.pres = pres

In [7]:
def classify2():

    SVM = svm.SVC(C=1, gamma='auto', kernel='linear', probability=True)
    SVM.fit(Train_X_final, y_train)
    predictions_SVM = SVM.predict(Test_X_final)

    acc = accuracy_score(predictions_SVM, y_test)
    CM = confusion_matrix(y_test, predictions_SVM)
    TN = CM[0][0]
    FN = CM[1][0]
    TP = CM[1][1]
    FP = CM[0][1]
    try :
        pres = TP/(TP+FP)
    except :
        pres = 0  
    accu = (TP+TN)/(TP+FP+TN+FN)
    recall = TP/(TP+FN)

    acc = accuracy_score(y_test, predictions_SVM)
    recll = recall_score(y_test, predictions_SVM)
    prec = precision_score(y_test, predictions_SVM)
    
    obj.setRecall(recall)
    obj.setPres(pres)
    
    print("Confusion Matrix")
    print(CM, "\n")
    return accu

In [8]:
obj = myClass()
acc_scores = []
presisi_scores = []
recall_scores = []
cv = KFold(n_splits=5, random_state=42, shuffle=True)
for train_index, test_index in cv.split(X):
    X_train, X_test, y_train, y_test = X[train_index], X[test_index], y[train_index], y[test_index]

    Test_X_final = matrixTransform(X_test)
    Train_X_final = matrixTransform(X_train)    
    print("Data Train :", len(X_train))
    print("Data Test :", len(X_test))

    acc= classify2()
    acc_scores.append(acc)
    presisi_scores.append(obj.getPres())
    recall_scores.append(obj.getRecall())

Data Train : 760
Data Test : 190
Confusion Matrix
[[74 18]
 [23 75]]

Data Train : 760
Data Test : 190
Confusion Matrix
[[78 27]
 [19 66]]

Data Train : 760
Data Test : 190
Confusion Matrix
[[73 29]
 [19 69]]

Data Train : 760
Data Test : 190
Confusion Matrix
[[66 16]
 [37 71]]

Data Train : 760
Data Test : 190
Confusion Matrix
[[69 25]
 [28 68]]

In [9]:
print("Pengujian Menggunakan Algoritma Support Vector Machine")
print("Accuracy :", acc_scores)
print("Presisi :", presisi_scores)
print("Recall :", recall_scores)
#print("Accuracy Average :", np.mean(acc_scores))
#print("Presisi Average :", np.mean(presisi_scores)) 
#print("Recall Average :", np.mean(recall_scores))

Pengujian Menggunakan Algoritma Support Vector Machine
Accuracy : [0.7842105263157895, 0.7578947368421053, 0.7473684210526316, 0.7210526315789474, 0.7210526315789474]
Presisi : [0.8064516129032258, 0.7096774193548387, 0.7040816326530612, 0.8160919540229885, 0.7311827956989247]
Recall : [0.7653061224489796, 0.7764705882352941, 0.7840909090909091, 0.6574074074074074, 0.7083333333333334]